import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { stdout } from "node:process";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(scriptDir, "../dist");
const immutableDir = join(distDir, "_astro");

function filesBelow(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? filesBelow(path) : [path];
  });
}

const publicShellFiles = [
  "site.webmanifest",
  "favicon.ico",
  "favicon.svg",
  "apple-touch-icon.png",
  "icon-192.png",
  "icon-512.png",
  "icon-maskable-512.png",
];
const shellPageFiles = ["index.html", "converters/index.html"].map((file) =>
  join(distDir, file),
);
const filesToPrecache = [
  ...filesBelow(immutableDir),
  ...publicShellFiles.map((file) => join(distDir, file)),
].sort();
const filesToRevise = [...filesToPrecache, ...shellPageFiles].sort();

for (const file of filesToRevise) {
  if (!statSync(file).isFile()) {
    throw new Error(`PWA precache entry is not a file: ${file}`);
  }
}

const toPublicUrl = (file) =>
  `/${relative(distDir, file).split(sep).join("/")}`;
const precacheUrls = [
  "/",
  "/converters",
  ...filesToPrecache.map(toPublicUrl),
].sort();

const revision = createHash("sha256")
  .update("curltocode-pwa-v2\0")
  .update(JSON.stringify(precacheUrls))
  .update("\0")
  .update(
    filesToRevise
      .map((file) =>
        createHash("sha256").update(readFileSync(file)).digest("hex"),
      )
      .join(""),
  )
  .digest("hex")
  .slice(0, 16);

const source = `/* Generated by scripts/generate-pwa.mjs. Do not edit directly. */
const CACHE_PREFIX = "curltocode-";
const PRECACHE = \`\${CACHE_PREFIX}precache-${revision}\`;
const PAGE_CACHE = \`\${CACHE_PREFIX}pages-${revision}\`;
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};
const PRECACHE_PATHS = new Set(PRECACHE_URLS);

self.addEventListener("install", (event) => {
  event.waitUntil(precacheShell());
});

async function precacheShell() {
  const cache = await caches.open(PRECACHE);
  await Promise.all(
    PRECACHE_URLS.map(async (url) => {
      // Bypass the browser HTTP cache so Cache Storage always receives a full
      // response body. Conditional responses can otherwise leave an install
      // looking successful while its JavaScript entries are unusable offline.
      const response = await fetch(
        new Request(url, {
          cache: "reload",
          credentials: "same-origin",
        }),
      );
      if (!response.ok) {
        throw new Error(\`Unable to precache \${url}: HTTP \${response.status}\`);
      }
      const bodySize = (await response.clone().arrayBuffer()).byteLength;
      if (bodySize === 0) {
        throw new Error(\`Unable to precache \${url}: empty response body\`);
      }
      await cache.put(url, response);
    }),
  );
}

self.addEventListener("activate", (event) => {
  event.waitUntil(
    Promise.all([
      caches
        .keys()
        .then((names) =>
          Promise.all(
            names
              .filter(
                (name) =>
                  name.startsWith(CACHE_PREFIX) &&
                  name !== PRECACHE &&
                  name !== PAGE_CACHE,
              )
              .map((name) => caches.delete(name)),
          ),
        ),
      self.registration.navigationPreload?.enable(),
      self.clients.claim(),
    ]),
  );
});

function canonicalPath(input) {
  const url = new URL(input, self.location.origin);
  return url.pathname === "" ? "/" : url.pathname;
}

async function cachePage(path) {
  const response = await fetch(path, { credentials: "same-origin" });
  if (!response.ok) return response;
  const contentType = response.headers.get("content-type") ?? "";
  if (!contentType.includes("text/html")) return response;
  const cache = await caches.open(PAGE_CACHE);
  await cache.put(canonicalPath(path), response.clone());
  return response;
}

async function navigationResponse(event) {
  const path = canonicalPath(event.request.url);
  try {
    const preload = await event.preloadResponse;
    const response = preload ?? (await fetch(event.request));
    if (response.ok) {
      const cache = await caches.open(PAGE_CACHE);
      await cache.put(path, response.clone());
    }
    return response;
  } catch {
    return (
      (await caches.match(path)) ??
      (await caches.match("/")) ??
      new Response("CurlToCode is unavailable offline.", {
        status: 503,
        headers: { "Content-Type": "text/plain; charset=utf-8" },
      })
    );
  }
}

async function cacheFirst(request, path) {
  const cached = await caches.match(path);
  if (cached !== undefined) return cached;
  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(PRECACHE);
    await cache.put(path, response.clone());
  }
  return response;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname === "/sw.js") return;

  if (request.mode === "navigate") {
    event.respondWith(navigationResponse(event));
    return;
  }

  if (url.pathname.startsWith("/_astro/") || PRECACHE_PATHS.has(url.pathname)) {
    event.respondWith(cacheFirst(request, url.pathname));
  }
});

self.addEventListener("message", (event) => {
  if (event.data?.type !== "CACHE_CURRENT_PAGE") return;
  const url = new URL(event.data.url, self.location.origin);
  if (url.origin !== self.location.origin) return;
  event.waitUntil(cachePage(canonicalPath(url.href)));
});
`;

writeFileSync(join(distDir, "sw.js"), source);
stdout.write(
  `Generated service worker ${revision} with ${precacheUrls.length} shell assets.\n`,
);
